source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

target 'CoreNetwork' do
  pod 'SnapKit', '~> 0.15.0'
  pod 'Alamofire', '~> 3.0.1'
  pod 'SwiftyJSON', '~> 2.3.0'
end